file:
  enabled: true
  fileName: "app.log"
  format: JSON   # or "string"
  level: INFO    # optional, can filter what gets logged to file

console:
  enabled: true
  format: STRING
  level: DEBUG

redaction:
  enabled: true
  fields: ["password", "token", "ssn"]
  patterns:
    - "cardNumber=\\d{16}"
    - "card\\s*=\\s*(\\d+)"
